
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: TRUE
    stdin_open: TRUE
    ports:
      - "12345:12345/udp"
      - "12345:12345/tcp"
    environment:
      #OS Options
      MAX_MEMORY: 12G

      #Server
      WORLD: 
      TYPE: PURPUR
      PURPUR_BUILD: LATEST
      EULA: "TRUE"
      VERSION: LATEST
      MOTD: "Pakour Server"
      DIFFICULTY: PEACEFUL
      MAX_PLAYERS: 15
      ALLOW_NETHER: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: TRUE
      ENABLE_COMMAND_BLOCK: TRUE
      FORCE_GAMEMODE: FALSE
      HARDCORE: FALSE
      MAX_BUILD_HEIGHT: 317
      SPAWN_ANIMALS: TRUE
      SPAWN_MONSTERS: TRUE
      SPAWN_NPCS: TRUE
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 7
      MODE: SURVIVAL
      PVP: TRUE
      ALLOW_FLIGHT: TRUE
      SERVER_NAME: "PARKOUR_SERVER"
      SERVER_PORT: 12345
      PLAYER_IDLE_TIMEOUT: 7
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 100
      FUNCTION_PERMISSION_LEVEL: 4
      OP_PERMISSION_LEVEL: 4
      PREVENT_PROXY_CONNECTIONS: FALSE
      SIMULATION_DISTANCE: 4
      EXEC_DIRECTLY: FALSE
      STOP_SERVER_ANNOUNCE_DELAY: 1
      ENFORCE_SECURE_PROFILE: FALSE
      #Custom Resource Pack
      
      #Whitelist
      
      #Rcon
      
      #Autopause
      # ENABLE_AUTOPAUSE: TRUE
      # MAX_TICK_TIME: -1
      # JVM_DD_OPTS: disable.watchdog=true
      
      #Autostop
      
      #Curseforge

      #Misc
      NETWORK_COMPRESSION_THRESHOLD: 256

    volumes:
      - ./data:/data

      - ./plugins:/data/plugins
      - ./datapacks:/data/world/datapacks
      
    restart: unless-stopped
